name: clean_on_pr_closed

on:
  pull_request:
    types: [ closed ]

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@v1.4
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      app_name: zonesage-web-app
      app_env: preview
      branch: ${{ github.event.pull_request.head.ref }}
