name: clean_on_delete

on: delete

jobs:
  clean:
    # only run when deleting a branch
    if: github.event.ref_type == 'branch'
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@v1.4
    concurrency:
      group: ci-preview-${{ github.event.ref }}
      cancel-in-progress: true
    with:
      app_name: zonesage-web-app
      app_env: preview
      branch: ${{ github.event.ref }}
