name: preview_on_pr_update

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  preview:
    # only run when updating an 'Open' PR
    if: github.event.pull_request.state == 'open'
    uses: jalantechnologies/github-ci/.github/workflows/ci.yml@v1.4
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      analyze_base: main
      app_name: zonesage-web-app
      app_env: preview
      app_hostname: '{1}.preview-zonesage.platform.jalantechnologies.com'
      branch: ${{ github.event.pull_request.head.ref }}
      build_args: |
        NODE_CONFIG_ENV=preview
      checks: "['npm:lint', 'compose:test', 'compose:e2e']"
